'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2032
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

'
'This source code was auto-generated by xsd, Version=1.1.4322.2032.
'
Namespace Yahoo.API.WebSearchSpellingResponse
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:yahoo:srch"),  _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="urn:yahoo:srch", IsNullable:=false)>  _
    Public Class ResultSet
        
        '<remarks/>
        Public Result As String
    End Class
End Namespace
